export const BACKEND_URL = '/api';

export const keywordDatabase = {
  technical: {
    label: 'Compétences techniques',
    keywords: [
      'python',
      'javascript',
      'typescript',
      'java',
      'c++',
      'c#',
      'php',
      'ruby',
      'swift',
      'kotlin',
      'react',
      'angular',
      'vue',
      'svelte',
      'next.js',
      'node.js',
      'express',
      'django',
      'flask',
      'spring',
      'html',
      'css',
      'sass',
      'tailwind',
      'bootstrap',
      'sql',
      'mysql',
      'postgresql',
      'mongodb',
      'redis',
      'firebase',
      'oracle',
      'docker',
      'kubernetes',
      'jenkins',
      'github actions',
      'gitlab ci',
      'ci/cd',
      'terraform',
      'ansible',
      'aws',
      'azure',
      'gcp',
      'cloud',
      'serverless',
      'rest',
      'graphql',
      'grpc',
      'api',
      'microservices',
      'machine learning',
      'deep learning',
      'ai',
      'data science',
      'nlp',
      'tensorflow',
      'pytorch',
      'agile',
      'scrum',
      'kanban',
      'jira',
      'confluence',
      'git',
      'linux',
      'bash',
      'powershell',
      'vim',
      'react native',
      'flutter',
      'android',
      'ios',
      'unit testing',
      'jest',
      'pytest',
      'cypress',
      'selenium',
      'redux',
      'context api',
      'zustand',
      'mobx',
      'webpack',
      'vite',
      'babel',
      'esbuild',
      'npm',
      'yarn',
      'design patterns',
      'solid',
      'clean architecture',
      'tdd',
      'ddd',
      'figma',
      'sketch',
      'adobe xd',
      'photoshop',
      'illustrator',
      'seo',
      'accessibility',
      'a11y',
      'responsive',
      'performance',
      'blockchain',
      'web3',
      'solidity',
    ],
  },
  soft: {
    label: 'Soft skills',
    keywords: [
      'communication',
      'leadership',
      "travail d'équipe",
      'teamwork',
      'autonomie',
      'autonomous',
      'gestion de projet',
      'project management',
      'résolution de problèmes',
      'problem solving',
      'créativité',
      'creativity',
      'adaptabilité',
      'adaptability',
      'curiosité',
      'curiosity',
      'rigueur',
      'rigor',
      'organisation',
      'organization',
      'gestion du temps',
      'time management',
      'esprit critique',
      'critical thinking',
      'négociation',
      'negotiation',
      'présentation',
      'presentation',
      'rédaction',
      'writing',
      'collaboration',
      'empathie',
      'empathy',
      'résilience',
      'resilience',
      'initiative',
      'polyvalence',
      'versatility',
      'pédagogie',
      'teaching',
      'prise de décision',
      'decision making',
      'management',
      'relation client',
      'customer relations',
      'service client',
      'customer service',
    ],
  },
  tools: {
    label: 'Outils & logiciels',
    keywords: [
      'excel',
      'word',
      'powerpoint',
      'outlook',
      'teams',
      'slack',
      'discord',
      'notion',
      'tableau',
      'power bi',
      'looker',
      'google analytics',
      'matomo',
      'salesforce',
      'hubspot',
      'zoho',
      'oracle crm',
      'sap',
      'oracle erp',
      'microsoft dynamics',
      'photoshop',
      'illustrator',
      'indesign',
      'premiere pro',
      'after effects',
      'final cut',
      'blender',
      'unity',
      'unreal engine',
      'matlab',
      'r',
      'spss',
      'stata',
      'sas',
      'minitab',
      'revit',
      'autocad',
      'solidworks',
      'catia',
      'trello',
      'asana',
      'basecamp',
      'clickup',
      'sentry',
      'datadog',
      'new relic',
      'grafana',
      'prometheus',
    ],
  },
  education: {
    label: 'Formation & diplômes',
    keywords: [
      'master',
      'bachelor',
      'licence',
      'doctorat',
      'phd',
      'dut',
      'bts',
      'bac+5',
      'bac+3',
      'bac+2',
      'ingénieur',
      'engineering',
      'informatique',
      'computer science',
      'marketing',
      'finance',
      'commerce',
      'business',
      'gestion',
      'management',
      'école de commerce',
      'business school',
      'université',
      'university',
      'alternance',
      'apprentissage',
      'stage',
      'internship',
      'formation',
      'certification',
      'certificate',
      'mooc',
      'coursera',
      'udemy',
      'udacity',
      'openclassrooms',
      'baccalauréat',
      'bac',
      'brevet',
      'master spécialisé',
      'mastère',
      'mba',
      'executive education',
      'rh',
      'ressources humaines',
      'psychologie',
      'sociologie',
      'droit',
      'law',
      'science politique',
      'political science',
      'architecture',
      'design',
      'art',
      'création',
    ],
  },
  languages: {
    label: 'Langues',
    keywords: [
      'français',
      'francais',
      'french',
      'anglais',
      'english',
      'espagnol',
      'spanish',
      'allemand',
      'german',
      'italien',
      'italian',
      'portugais',
      'portuguese',
      'chinois',
      'mandarin',
      'japonais',
      'japanese',
      'arabe',
      'arabic',
      'bilingue',
      'bilingual',
      'courant',
      'fluent',
      'native',
      'langue maternelle',
      'toeic',
      'toefl',
      'ielts',
      'cambridge',
      'dalf',
      'delf',
      'tcf',
      'niveau c1',
      'niveau c2',
      'niveau b2',
      'niveau b1',
    ],
  },
  experience: {
    label: 'Expérience & secteurs',
    keywords: [
      'stage',
      'internship',
      'alternance',
      'apprentissage',
      'cdi',
      'cdd',
      'freelance',
      'développement',
      'development',
      'web',
      'mobile',
      'logiciel',
      'software',
      'data',
      'analyse',
      'analysis',
      'business intelligence',
      'bi',
      'cybersécurité',
      'cybersecurity',
      'sécurité',
      'security',
      'devops',
      'sre',
      'infrastructure',
      'sysadmin',
      'network',
      'marketing digital',
      'digital marketing',
      'seo',
      'sea',
      'social media',
      'commerce',
      'sales',
      'business development',
      'commercial',
      'finance',
      'comptabilité',
      'accounting',
      'audit',
      'contrôle de gestion',
      'ressources humaines',
      'human resources',
      'recrutement',
      'recruitment',
      'conseil',
      'consulting',
      'strategy',
      'stratégie',
      'logistique',
      'logistics',
      'supply chain',
      'achats',
      'procurement',
      'enseignement',
      'education',
      'formation',
      'training',
      'santé',
      'health',
      'médical',
      'medical',
      'soins',
      'care',
      'immobilier',
      'real estate',
      'construction',
      'btp',
      'hôtellerie',
      'hospitality',
      'tourisme',
      'tourism',
      'restauration',
      'agriculture',
      'agroalimentaire',
      'food',
      'environnement',
      'environment',
      'design',
      'ux',
      'ui',
      'product design',
      'graphic design',
      'product management',
      'product owner',
      'chef de produit',
      'chef de projet',
      'project manager',
      'scrum master',
      'support',
      'helpdesk',
      'assistance',
      'technicien',
      'technician',
    ],
  },
};

export const SCORE_THRESHOLDS = { excellent: 80, good: 60, average: 40, low: 20 };

export const analyzeStepLabels = [
  'Lecture du CV',
  'Extraction des compétences',
  "Comparaison à l'offre",
  'Calcul du score pondéré',
];
